default_language_version:
    python: python3.11
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types: [ python ]
-   repo: local
    hooks:
      - id: isort
        name: isort (python)
        entry: isort
        language: system
        types: [ python ]

-   repo: local
    hooks:
      - id: rust-linting
        name: Rust linting
        description: Run cargo fmt on files included in the commit. rustfmt should be installed before-hand.
        entry: cargo fmt --all --
        pass_filenames: true
        types: [file, rust]
        language: system
-   repo: local                                                                                                                                    
    hooks:
      - id: rust-clippy
        name: Rust clippy
        description: Run cargo clippy on files included in the commit. clippy should be installed before-hand.
        entry: cargo clippy --all-targets --all-features -- -Dclippy::all
        pass_filenames: false
        types: [file, rust]
        language: system
