[package]
name = "boom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amqprs = "1.6.2"
apache-avro = "0.16.0"
serde = "1.0.203"
serde_bytes = "0.11.14"
serde_json = "1.0.117"
serde_with = "3.8.1"
tokio = "1.38.0"

[dependencies.mongodb]
version = "2.8.2"
features = ["tokio-runtime"]
