name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Configure cache
      uses: Swatinem/rust-cache@v2
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: 7.0.0
    - uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: "7.x"
    - run: redis-cli ping
    - name: Edit test config
      run: |
        sed -i 's/username: mongoadmin/username:/g' tests/config.test.yaml
        sed -i 's/password: mongoadminsecret/password:/g' tests/config.test.yaml
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose