name: rabbitmq and mongo
                                                                                
on:                                                                             
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:latest
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672
        options:
          --health-cmd "rabbitmqctl node_health_check"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        pip install pip==24.0
        pip install pika

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: 7.0
        mongodb-db: test
        mongodb-port: 27017

    - name: Check MongoDB is up
      run: |
        curl http://localhost:27017

    - name: Check rabbitmq is up
      run: |
        python tests/send.py
        python tests/receive.py
      env:
        RABBITMQ_HOST: 127.0.0.1
        RABBITMQ_PORT: ${{ job.services.rabbitmq.ports['5672'] }}

    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: |
        cargo test --verbose
      env:
        RABBITMQ_HOST: 127.0.0.1
        RABBITMQ_PORT: ${{ job.services.rabbitmq.ports['5672'] }}

