name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions: write-all
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        test_subset:
          [
            "unit_tests",
            "benchmark",
          ]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
        clean: false
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Configure cache
      uses: Swatinem/rust-cache@v2
    # load the cached docker images
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build docker-compose
      run: docker buildx bake --file docker-compose.yaml --file .github/workflows/docker-compose-cache.json
    - name: Run docker-compose
      run: docker compose up --build -d
    - name: Tests
      if: ${{ matrix.test_subset == 'unit_tests' }}
      run: cargo test --release
    - name: Filter benchmark
      if: ${{ matrix.test_subset == 'benchmark' }}
      run: cargo bench filter_benchmark --
